version: "3.6"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - .:/code
    command: scrapy crawl news -a 'url=https://www.economist.com/leaders/2021/01/16/why-a-dawn-of-technological-optimism-is-breaking,https://foreignpolicy.com/2021/01/14/tokyo-olympics-2020-japan-public-opinion/'
